README.md
I found this article when browsing researches using geometric morphometry, which includes some raw data and R code! :) It might be suitable for the replication assignment for stone artifacts in the future!
=> added one reference

README.md
Adding two references with links to open data/R packages that include the data (Price, et al. 2016; Wolfhagen and Price 2017)
=> Adding some references to the citation list (Price, et al. 2016; Wolfhagen and Price 2017)

README.md
Hi Ben,
Just added my PlosOne 2019 paper to the references list.
Best,
J.
=> added Cascalheira (2019) to references

README.md
=> added Wang & Marwick two papers in 2020

README.md
Includes code for k-means and falloff curves applied to British Neolithic axes.
=> Added my paper with Andy Bevan and others

README.md
Added 'Visibility of the Gask Ridge road from simulated Watchtowers: A Monte Carlo testing approach.' journal article. Code to reproduce analysis available at 10.5281/zenodo.3953468
=> added Lewis (2020)

README.md
Adding our article (includes SI with code) + GitHub repo. Compositional analysis and lead isotope analysis of bronze objects from a hoard.
=> add Danielisova, Pajdla, Bursak et al. 2021

README.md
As you suggested, I added myself as a contributor, as well as adding the **bioanth** package with a description.
=> add bioanth package

README.md
...beneath "Other partitioning methods" as shameless self-promotion.
Didn't add it to the CRAN taskview though, as it's not restricted to archaeological research questions.
=> added the percopackage to the Readme

README.md
Added a new package, folio. Also added a package requested in the ctv-archaeology issues, neotoma
=> add packages to datasets

README.md
Hello, Please consider to add this publication.
=> Add Will et al. 2022

README.md
Hello Ben,
The R Code can be found in the Zenodo link (Supplementary + Open Materials Section).
Best, Chris
=> Add Sommer et al. 2022

README.md
Reproducible R Code can be found on Zenodo: https://doi.org/10.5281/zenodo.5883926 Best, Chris
=> Add Dapschauskas et al. 2022

README.md
Add [archeofrag](https://github.com/sebastien-plutniak/archeofrag) in the "simulation" section (although it might also enter in the "network" section, or in a new section dedicated to field data analysis).
=> add archeofrag package

Archaeology.md
No changes in the rest of the order, just puts CRAN packages first.
=> reorders to put CRAN packages first in each section

Archaeology.md
Thanks again for inviting me! I wanted to make some suggestions on (consistent) spelling and format. 
There's also: 
* one addition, the R-Package [unstruwwel](https://github.com/stefanieschneider/unstruwwel) (also on CRAN), which transforms strings describing chronology into a numerical representation 
* I put datplot in the data-set category as well, since it ships with a data set of ~2500 inscriptions from Bithynia
=> some suggestions

Archaeology.md
Add two packages: `dendroNetwork` and `fellingdater`.
=> Add packages for dendrochronology

Archaeology.md
Add core packages and reorganize content as discussed in #60.
=> Add core packages

README.md
Adds 11 papers with R code from 2023 and 2024. It's not very systematic I'm afraid; I just scanned through my reference manager.
=> Papers from 2023 and 2024

Archaeology.md
I am late, I know... ;) But as suggested in #71 I got around to submitting to CRAN last week and they did accept it today... so yay.
=> clayringsmiletus now on CRAN
